---
# tasks file for radarr :: install
- debug:
    msg:
      - "###########################"
      - "##                       ##"
      - "##   radarr -- install   ##"
      - "##                       ##"
      - "###########################"
- name: Download Radarr
  get_url:
    url: "{{ radarr_url }}"
    dest: /tmp/radarr.tar.gz
  notify: empty_/opt/Radarr
- meta: flush_handlers
- name: Extract radarr.tar.gz
  unarchive:
    src: /tmp/radarr.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/Radarr/Radarr.exe
- name: Set owner on radarr folder
  file:
    path: /opt/Radarr
    owner: radarr
    group: radarr
    state: directory
    recurse: yes
- name: Add SystemD Unit File
  copy:
    src: radarr.service
    dest: /etc/systemd/system/radarr.service
- name: Start Radarr Service
  systemd:
    name: radarr
    state: started
    enabled: yes
    daemon_reload: yes
