---
# tasks file for radarr :: network
- debug:
    msg:
    - "###########################"
    - "##                       ##"
    - "##   radarr -- network   ##"
    - "##                       ##"
    - "###########################"
- name: Add Firewall File for Radarr
  copy:
    src: radarr.xml
    dest: /etc/firewalld/services/radarr.xml
  notify: reload_firewalld
- name: Open FirewallD Port
  firewalld:
    service: radarr
    immediate: yes
    permanent: yes
    state: enabled
