---
# handlers file for radarr
- name: reload_firewalld
  systemd:
    name: firewalld
    state: reloaded
- name: empty_/opt/Radarr
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/opt/Radarr/*"
